blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::delete('products/destroyAll', 'ProductController@destroyAll')->name('products.destroyAll');
Route::resource('products', 'ProductController');
Route::resource('ratings', 'RatingController');
Route::resource('comments', 'CommentController');
Route::resource('taxdiscount', 'TaxDiscountController');

blog/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

    protected $guarded =['id'];

    public function ratings(){
        return $this->hasMany('App\Rating', 'product_id', 'id')->get();
    }

    public function comments() {
        return $this->hasMany('App\Comment', 'product_id', 'id')->orderBy( 'created_at', 'DESC' );
    }

    public function taxes(){

        $taxes = Tax::orderBy('created_at', 'desc')->first();

        return $taxes;
    }

    public function discounts(){

        $discounts = GlobalDiscount::orderBy('created_at', 'desc')->first();

        return $discounts;
    }

    public function tax(){

        //$tax_perc = session('tax')/100;
        $default = 0.21;
        if(isset($this->taxes()->tax)){
            $tax_perc = $this->taxes()->tax / 100;
            $tax = $this->base_price * $tax_perc;
        } else {
            $tax = $this->base_price * $default;
        }

        return $tax;
    }

    public function global_discount(){

        $global_discount = 0;
        if(isset($this->discounts()->global_discount)){
//            $discount = session('global_discount')/100;
            $discount = $this->discounts()->global_discount / 100;
            $global_discount = $this->base_price * $discount;
        }


        return $global_discount;
    }

    public function base_price(){

        $base_price = $this->base_price + $this->tax();

        return $base_price;
    }

    public function special_price(){
        $special_price = 0;
        if(isset($this->individual_discount)){
            $special_price = $this->base_price + $this->tax() - $this->individual_discount;
        }elseif($this->individual_discount == NULL && $this->global_discount() > 0){
            $special_price = $this->base_price + $this->tax() - $this->global_discount();
        }

        return $special_price;
    }
}

blog/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\GlobalDiscount;
use App\Http\Requests\ProductRequest;
use App\Product;
use App\Rating;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(isset(Auth::user()->role) && Auth::user()->role == 'user' || Auth::user() != true){
            $products = Product::where('status', '=', 'enabled')->paginate(8);
        } elseif(isset(Auth::user()->role) && Auth::user()->role == 'admin') {
            $products = Product::paginate(8);
        }

        return view('products.index', [
            'products' => $products
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request, Product $product)
    {
        $input = $request->except(['image']);

        if($request->hasFile('image')){
            $imagePath = $request->file('image')->store('product-images');
            $product->image = $imagePath;
        }

        $product->fill($input)->save();

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $rating = Rating::where('product_id', '=', $product->id)->get();

        $ratings = false;

        if(isset(Auth::user()->id)){
            foreach ($rating as $r){
                if($r->user_id == Auth::user()->id){
                    $ratings = true;
                }
            }
        }
//dd(session('tax'));

        $totalRate = 0;
        $i = 0;
        $sum = 0;
        $countRate = 0;

        foreach ($rating as $rate){
            $totalRate += $rate->rating;
            $sum = ++$i;
        }
        if($totalRate > 0){
            $countRate = number_format(($totalRate / $sum), 1);
        }




        return view('products.show', [
            'product' => $product,
            'countRate' => $countRate,
            'ratings' => $ratings,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', [
            'product' => $product,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $input = $request->except(['image']);

        if($request->hasFile('image')){
            Storage::delete($product->image);
            $imagePath = $request->file('image')->store('product-images');
            $product->image = $imagePath;
        }

        $product->fill($input)->save();

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        Storage::delete($product->image);
        $product->delete();

        return redirect()->route('products.index');
    }

    public function destroyAll(Request $request)
    {
        $file = new Filesystem;

        $file->cleanDirectory('../storage/app/public/product-images');
        Product::where('id', '>', -1)->delete();

        return redirect()->route('products.index');
    }

}

blog/resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
                    @csrf
                    <label>Title:</label>
                    <input class="form-control" name="title" type="text">
                    <label>Description:</label>
                    <textarea id="example" class="form-control" name="description"></textarea>
                    <label>Base price:</label>
                    <input class="form-control" name="base_price" type="text">
                    <label>Individual discount:</label>
                    <input class="form-control" name="individual_discount" type="text">
                    <label>Item image:</label>
                    <input class="form-control" name="image" type="file">
                    <label>Status:</label>
                    <select class="form-control" name="status" required>
                        <option selected value="enabled">Enabled</option>
                        <option value="disabled">Disabled</option>
                    </select>
                    <input type="submit" class="btn btn-primary" value="Add new product item">
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form method="post" action="{{ route('products.update', [$product->id]) }}" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <label>Title:</label>
                    <input class="form-control" name="title" type="text" value="{{ $product->title }}">
                    <label>Description:</label>
                    <textarea id="example" class="form-control" name="description">{{ $product->description }}</textarea>
                    <label>Base price:</label>
                    <input class="form-control" name="base_price" type="text" value="{{ $product->base_price }}">
                    <label>Individual discount:</label>
                    <input class="form-control" name="individual_discount" type="text" value="{{ $product->individual_discount }}">
                    <label>Item image:</label>
                    <input class="form-control" name="image" type="file">
                    <label>Status: {{ $product->status }}</label>
                    <select class="form-control" name="status" required>
                        <option value="enabled">Enabled</option>
                        <option value="disabled">Disabled</option>
                    </select>
                    <input type="submit" class="btn btn-primary" value="Update product item">
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @include('components.products-item')
            @include('components.admin-product-management')
        </div>
        <div>
            {{ $products->links() }}
        </div>
    </div>
@endsection

blog/resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div>
                    <h2>{{ $product->title }}</h2>
                    @if(isset($product->image))
                        @if(strpos($product->image, "https://") !== false || (strpos($product->image, "http://") !== false))
                            <img src="{{ $product->image }}" style="max-width: 500px; max-height: 500px;" />
                        @else
                            <img src="{{ Storage::url($product->image) }}" style="max-width: 500px; max-height: 500px;" />
                        @endif
                    @endif
                    <div class="container">
                        <span id="rateMe1"></span>
                    </div>
                    @include('components.ratings')
                    @if(isset($product->individual_discount) || $product->global_discount() > 0)
                        <li>
                            Base price with tax: <s>{{ number_format($product->base_price(), 2) }}</s>€
                        </li>
                        <li>
                            Special price: {{ number_format($product->special_price(), 2) }}€
                        </li>
                    @else
                        <li>
                            Base price with tax: {{ number_format($product->base_price(), 2) }}€
                        </li>
                    @endif
                    <p class="fr-view">{!! $product->description !!}</p>
                </div>
            </div>
            <div class="col-md-6">

                <h2>Comments</h2>
                @include('components.comments-form')
                @include('components.comments-list')
            </div>
        </div>
    </div>
@endsection